{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1 # Common Traefik API version for Middleware
kind: Middleware
metadata:
  name: {{ .Release.Name }}-strip-couchdb
  namespace: {{ .Release.Namespace }} # Deploys middleware in the same namespace as the release
  labels:
    app.kubernetes.io/name: {{ include "vibe-cloud-instance.fullname" . }}
    helm.sh/chart: {{ include "vibe-cloud-instance.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: couchdb-middleware
spec:
  stripPrefix:
    prefixes:
      - /couchdb
{{- end }}
