{{- if .Values.ingress.enabled -}}
apiVersion: {{ include "vibe-cloud-instance.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "vibe-cloud-instance.couchdb.fullname" . }}-fauxton
  namespace: {{ include "vibe-cloud-instance.namespace" . }}
  labels:
    {{- include "vibe-cloud-instance.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb-fauxton-ingress
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and (.Values.ingress.className) (eq (include "vibe-cloud-instance.ingress.apiVersion" .) "networking.k8s.io/v1") }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.instanceIdentifier }}.{{ .Values.ingress.mainDomain }}
      http:
        paths:
          - path: /_utils
            pathType: Prefix
            backend:
              {{- if eq (include "vibe-cloud-instance.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ include "vibe-cloud-instance.couchdb.fullname" . }}
                port:
                  number: {{ .Values.couchdb.service.port }}
              {{- else }}
              serviceName: {{ include "vibe-cloud-instance.couchdb.fullname" . }}
              servicePort: {{ .Values.couchdb.service.port }}
              {{- end }}
          - path: /_session
            pathType: Prefix
            backend:
              {{- if eq (include "vibe-cloud-instance.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ include "vibe-cloud-instance.couchdb.fullname" . }}
                port:
                  number: {{ .Values.couchdb.service.port }}
              {{- else }}
              serviceName: {{ include "vibe-cloud-instance.couchdb.fullname" . }}
              servicePort: {{ .Values.couchdb.service.port }}
              {{- end }}
          - path: /_all_dbs
            pathType: Prefix
            backend:
              {{- if eq (include "vibe-cloud-instance.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ include "vibe-cloud-instance.couchdb.fullname" . }}
                port:
                  number: {{ .Values.couchdb.service.port }}
              {{- else }}
              serviceName: {{ include "vibe-cloud-instance.couchdb.fullname" . }}
              servicePort: {{ .Values.couchdb.service.port }}
              {{- end }}
          - path: /
            pathType: Prefix
            backend:
              {{- if eq (include "vibe-cloud-instance.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ include "vibe-cloud-instance.couchdb.fullname" . }}
                port:
                  number: {{ .Values.couchdb.service.port }}
              {{- else }}
              serviceName: {{ include "vibe-cloud-instance.couchdb.fullname" . }}
              servicePort: {{ .Values.couchdb.service.port }}
              {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        - {{ .Values.instanceIdentifier }}.{{ .Values.ingress.mainDomain }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- else if (hasKey .Values.ingress.annotations "cert-manager.io/cluster-issuer") }}
  tls:
    - hosts:
        - {{ .Values.instanceIdentifier }}.{{ .Values.ingress.mainDomain }}
      secretName: {{ .Values.instanceIdentifier }}-tls
  {{- end }}
{{- end }}
