{{- /*
Create secrets for CouchDB and JWT if they are enabled and not using an existing secret.
*/}}
{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vibe-cloud-instance.fullname" . }}-couchdb-creds
  labels:
    {{- include "vibe-cloud-instance.labels" . | nindent 4 }}
type: Opaque
data:
  {{- /* Use provided username or generate one */}}
  username: {{ .Values.couchdb.auth.username | default (randAlphaNum 10) | b64enc | quote }}
  {{- /* Use provided password or generate one */}}
  password: {{ .Values.couchdb.auth.password | default (randAlphaNum 32) | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vibe-cloud-instance.fullname" . }}-jwt-secret
  labels:
    {{- include "vibe-cloud-instance.labels" . | nindent 4 }}
type: Opaque
data:
  {{- /* Use provided secret or generate one */}}
  secret: {{ .Values.vibeApp.auth.jwtSecret | default (randAlphaNum 64) | b64enc | quote }}
{{- end }}
