apiVersion: {{ include "vibe-cloud-instance.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "vibe-cloud-instance.vibeApp.fullname" . }}
  namespace: {{ include "vibe-cloud-instance.namespace" . }}
  labels:
    {{- include "vibe-cloud-instance.labels" . | nindent 4 }}
    app.kubernetes.io/component: vibe-app
spec:
  replicas: {{ .Values.vibeApp.replicaCount }}
  selector:
    matchLabels:
      {{- include "vibe-cloud-instance.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: vibe-app
  template:
    metadata:
      labels:
        {{- include "vibe-cloud-instance.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: vibe-app
    spec:
      containers:
        - name: vibe-cloud-app
          image: {{ include "vibe-cloud-instance.vibeApp.image" . }}
          imagePullPolicy: {{ .Values.vibeApp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.vibeApp.service.targetPort }}
              protocol: TCP
          env:
            - name: APP_PORT
              value: {{ .Values.vibeApp.service.targetPort | quote }}
            # TODO: Consider creating a Kubernetes secret for CouchDB credentials and JWT_SECRET
            # and referencing them here using valueFrom.secretKeyRef
            - name: COUCHDB_URL
              value: "http://{{ include "vibe-cloud-instance.couchdb.fullname" . }}:{{ .Values.couchdb.service.port }}"
            # Source credentials from the Kubernetes secret
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  # Use the secret name defined in _helpers.tpl
                  name: {{ include "vibe-cloud-instance.couchdbSecretName" . | quote }}
                  key: username
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Use the secret name defined in _helpers.tpl
                  name: {{ include "vibe-cloud-instance.couchdbSecretName" . | quote }}
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  # Use the secret name defined in _helpers.tpl
                  name: {{ include "vibe-cloud-instance.jwtSecretName" . | quote }}
                  key: secret
            - name: S3_ENABLED
              value: "false" # Defaulting to false as per current setup
            {{- range $key, $value := .Values.vibeApp.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.vibeApp.resources }}
          resources:
            {{- toYaml .Values.vibeApp.resources | nindent 12 }}
          {{- end }}
