# /docker-compose.yml
networks:
    vibe_net:
        driver: bridge

volumes:
    couchdb_data:
    minio_data:

services:
    vibe-cloud:
        build:
            context: . # <--- CHANGE: Use monorepo root as context
            dockerfile: ./apps/vibe-cloud/Dockerfile # <--- CHANGE: Specify Dockerfile path relative to root
        container_name: vibe_cloud_service
        restart: unless-stopped
        ports:
            - "3000:3000"
        networks:
            - vibe_net
        depends_on:
            - couchdb
            - minio
        environment:
            - COUCHDB_URL=http://admin:password@couchdb:5984
            - MINIO_ENDPOINT=minio
            - MINIO_PORT=9000
            - MINIO_ACCESS_KEY=minioadmin
            - MINIO_SECRET_KEY=minioadmin
            - MINIO_USE_SSL=false
            - JWT_SECRET=your-super-secret-jwt-key # CHANGE THIS IN PRODUCTION

    couchdb:
        # ... (rest of couchdb config is fine)
        image: couchdb:latest
        container_name: vibe_couchdb
        restart: unless-stopped
        ports:
            - "5984:5984"
        networks:
            - vibe_net
        volumes:
            - couchdb_data:/opt/couchdb/data
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=password # CHANGE THIS IN PRODUCTION

    minio:
        # ... (rest of minio config is fine)
        image: minio/minio:latest
        container_name: vibe_minio
        restart: unless-stopped
        ports:
            - "9000:9000"
            - "9001:9001"
        networks:
            - vibe_net
        volumes:
            - minio_data:/data
        environment:
            - MINIO_ROOT_USER=minioadmin # CHANGE THIS IN PRODUCTION
            - MINIO_ROOT_PASSWORD=minioadmin # CHANGE THIS IN PRODUCTION
        command: server /data --console-address ":9001"
