version: "3.8"

services:
    vibe-cloud:
        build:
            context: ./vibe-cloud # Path to the directory containing the Dockerfile
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - ./vibe-cloud/.env # Load environment variables from .env file
        ports:
            # Map host port (left) to container port (right, from APP_PORT in .env or default 3000)
            # Use the format "HOST_PORT:CONTAINER_PORT"
            # Example: "3000:3000" maps host port 3000 to container port 3000
            # You can change the host port if 3000 is already in use on your machine.
            - "${APP_PORT:-3000}:${APP_PORT:-3000}"
        networks:
            - vibe-net
        depends_on:
            - couchdb # Ensure CouchDB starts before the app

    couchdb:
        image: couchdb:latest # Use the official CouchDB image
        restart: unless-stopped
        env_file:
            - ./vibe-cloud/.env # Load ALL variables from .env into the container environment
        # environment: # Removed redundant block - CouchDB image reads COUCHDB_USER/PASSWORD from env loaded by env_file
        #     - COUCHDB_USER=${COUCHDB_USER}
        #     - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
        ports:
            # Map host port 5984 to container port 5984 (CouchDB default)
            - "5984:5984"
        volumes:
            # Persist CouchDB data using a named volume
            - couchdb-data:/opt/couchdb/data
        networks:
            - vibe-net

networks:
    vibe-net:
        driver: bridge

volumes:
    couchdb-data: # Define the named volume for CouchDB data persistence
