apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: couchdb
    namespace: vibe-cloud-services
spec:
    serviceName: "couchdb"
    replicas: 1 # Start with a single node for simplicity
    selector:
        matchLabels:
            app: couchdb
    template:
        metadata:
            labels:
                app: couchdb
        spec:
            containers:
                - name: couchdb
                  image: couchdb:3.3 # Specify a version, 3.3 is a common stable one
                  ports:
                      - containerPort: 5984
                        name: couchdb-port
                  env:
                      - name: COUCHDB_USER
                        value: "admin" # Replace with a secure password, perhaps from a Secret
                      - name: COUCHDB_PASSWORD
                        value: "password" # Replace with a secure password, perhaps from a Secret
                  volumeMounts:
                      - name: couchdb-data
                        mountPath: /opt/couchdb/data
    volumeClaimTemplates:
        - metadata:
              name: couchdb-data
          spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                  requests:
                      storage: 5Gi # Adjust storage size as needed
              # storageClassName: "scw-bss-gp2" # For Scaleway, if a specific class is needed and configured
