apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vibe-cloud-ui
  labels:
    app: vibe-cloud-ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vibe-cloud-ui