apiVersion: {{ include "vibe-cloud-instance.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "vibe-cloud-instance.couchdb.fullname" . }}
  namespace: {{ include "vibe-cloud-instance.namespace" . }}
  labels:
    {{ include "vibe-cloud-instance.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb
spec:
  serviceName: {{ include "vibe-cloud-instance.couchdb.fullname" . }}
  replicas: 1 # For now, single replica. Can be parameterized later if needed.
  selector:
    matchLabels:
      {{ include "vibe-cloud-instance.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: couchdb
  template:
    metadata:
      labels:
        {{ include "vibe-cloud-instance.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: couchdb
    spec:
      containers:
        - name: couchdb
          image: {{ include "vibe-cloud-instance.couchdb.image" . }}
          imagePullPolicy: {{ .Values.couchdb.image.pullPolicy }}
          ports:
            - name: couchdb
              containerPort: {{ .Values.couchdb.service.port }}
              protocol: TCP
          env:
            # Source credentials from the Kubernetes secret
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  # Use the secret name defined in _helpers.tpl (based on fullname) or the one provided in values
                  name: {{ include "vibe-cloud-instance.couchdbSecretName" . | quote }}
                  key: username
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vibe-cloud-instance.couchdbSecretName" . | quote }}
                  key: password
            # Add other CouchDB environment variables if needed
          {{- if .Values.couchdb.persistence.enabled }}
          volumeMounts:
            - name: couchdb-data
              mountPath: /opt/couchdb/data
          {{- end }}
          {{- if .Values.couchdb.resources }}
          resources:
            {{- toYaml .Values.couchdb.resources | nindent 12 }}
          {{- end }}
  {{- if .Values.couchdb.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: couchdb-data
        labels:
          {{ include "vibe-cloud-instance.labels" . | nindent 10 }}
          app.kubernetes.io/component: couchdb
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.couchdb.persistence.size }}
        {{- if .Values.couchdb.persistence.storageClassName }}
        storageClassName: {{ .Values.couchdb.persistence.storageClassName | quote }}
        {{- end }}
  {{- end }}
