{{- if .Values.ingress.enabled -}}
apiVersion: {{ include "vibe-cloud-instance.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "vibe-cloud-instance.vibeApp.fullname" . }}
  namespace: {{ include "vibe-cloud-instance.namespace" . }}
  labels:
    {{- include "vibe-cloud-instance.labels" . | nindent 4 }}
    app.kubernetes.io/component: vibe-app-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and (.Values.ingress.className) (eq (include "vibe-cloud-instance.ingress.apiVersion" .) "networking.k8s.io/v1") }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ include "vibe-cloud-instance.ingress.host" . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              {{- if eq (include "vibe-cloud-instance.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ include "vibe-cloud-instance.vibeApp.fullname" . }}
                port:
                  number: {{ .Values.vibeApp.service.port }}
              {{- else }}
              # For older ingress apiVersions
              serviceName: {{ include "vibe-cloud-instance.vibeApp.fullname" . }}
              servicePort: {{ .Values.vibeApp.service.port }}
              {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        - {{ include "vibe-cloud-instance.ingress.host" $ | quote }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- else if (index .Values.ingress.annotations "cert-manager.io/cluster-issuer") }}
  # If cert-manager annotation is present, assume it will handle TLS
  tls:
    - hosts:
        - {{ include "vibe-cloud-instance.ingress.host" . | quote }}
      # cert-manager will create a secret with this name, or use an existing one if specified
      # Defaulting to a name based on the instance identifier for cert-manager to create
      secretName: {{ .Values.instanceIdentifier }}-tls
  {{- end }}
{{- end }}
