{{- if .Values.couchdb.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-couchdb-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.config.couchdbPublicUrl | trimPrefix "https://" | quote }}
      secretName: {{ .Release.Name }}-couchdb-tls
  rules:
    - host: {{ .Values.config.couchdbPublicUrl | trimPrefix "https://" | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-couchdb
                port:
                  number: 5984
{{- end }}