apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  JWT_SECRET: {{ .Values.config.jwtSecret | b64enc }}
  INSTANCE_ID_SECRET: {{ .Values.config.instanceIdSecret | b64enc }}
  COUCHDB_USER: {{ .Values.couchdb.auth.username | b64enc }}
  COUCHDB_PASSWORD: {{ .Values.couchdb.auth.password | b64enc }}
  SCALEWAY_ACCESS_KEY: {{ .Values.config.scalewayAccessKey | b64enc }}
  SCALEWAY_SECRET_KEY: {{ .Values.config.scalewaySecretKey | b64enc }}