apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  JWT_SECRET: {{ .Values.config.jwtSecret | b64enc }}
  INSTANCE_ID_SECRET: {{ .Values.config.instanceIdSecret | b64enc }}
  SCALEWAY_ACCESS_KEY: {{ .Values.config.scalewayAccessKey | b64enc }}
  SCALEWAY_SECRET_KEY: {{ .Values.config.scalewaySecretKey | b64enc }}
  ENCRYPTION_MASTER_KEY: {{ .Values.config.encryptionMasterKey | b64enc }}
  SESSION_SECRET: {{ (default .Values.config.jwtSecret .Values.config.sessionSecret) | b64enc }}
