version: "3.8"

services:
    vibe-cloud-api: # Renamed from vibe-cloud
        build:
            context: ./vibe-cloud/vibe-cloud-api # Updated context path
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - ./vibe-cloud/vibe-cloud-api/.env # Updated env_file path
        ports:
            # API service port (default 3000)
            - "${APP_PORT:-3000}:${APP_PORT:-3000}" # Keep using APP_PORT for API
        networks:
            - vibe-net
        depends_on:
            couchdb:
                condition: service_started
            minio:
                condition: service_started

    vibe-cloud-control-plane:
        build:
            context: ./vibe-cloud/vibe-cloud-control-plane
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            # Assumes control plane might have its own .env or share API's
            - ./vibe-cloud/vibe-cloud-control-plane/.env
        ports:
            # Control plane service port (default 3001)
            - "${CONTROL_PLANE_PORT:-3001}:${CONTROL_PLANE_PORT:-3001}"
        networks:
            - vibe-net
        depends_on:
            couchdb: # Control plane uses DataService/AuthService which need CouchDB
                condition: service_started

    couchdb:
        image: couchdb:latest
        restart: unless-stopped
        env_file:
            - ./vibe-cloud/vibe-cloud-api/.env # Point to API's .env for credentials
        ports:
            # Map host port 5984 to container port 5984
            - "5984:5984"
        volumes:
            # Persist CouchDB data using a named volume
            - couchdb-data:/opt/couchdb/data
        networks:
            - vibe-net

    minio:
        image: minio/minio:latest
        restart: unless-stopped
        env_file:
            - ./vibe-cloud/vibe-cloud-api/.env # Point to API's .env for credentials
        environment:
            # Use variables loaded by env_file for root credentials
            - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
            - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
        ports:
            # Map host port 9000 to container port 9000 (Minio API)
            - "${MINIO_PORT:-9000}:9000"
            # Map host port 9001 to container port 9001 (Minio Console)
            - "9001:9001"
        volumes:
            # Persist Minio data using a named volume
            - minio-data:/data
        command: server /data --console-address ":9001"
        networks:
            - vibe-net

networks:
    vibe-net:
        driver: bridge

volumes:
    couchdb-data: # Define the named volume for CouchDB data persistence
    minio-data: # Define the named volume for Minio data persistence
