# Default values for vibe-cloud-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
    repository: rg.fr-par.scw.cloud/vibe-registry/vibe-cloud-api
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

service:
    type: ClusterIP
    port: 80

config:
    # Sensitive values are now in secrets.yaml
    jwtSecret: ""
    instanceIdSecret: ""
    couchdbUser: ""
    couchdbPassword: ""
    scalewayAccessKey: ""
    scalewaySecretKey: ""

    # Non-sensitive values
    couchdbUrl: "http://{{ .Release.Name }}-couchdb:5984"
    storageProvider: "scaleway"
    scalewayRegion: "fr-par"
    scalewayEndpoint: "s3.fr-par.scw.cloud"
    corsOrigin: "http://127.0.0.1:3000" # This will be overridden by the production URL
    port: "5050"

# CouchDB sub-chart configuration
couchdb:
    enabled: true
    auth:
        username: "" # Provided in secrets.yaml
        password: "" # Provided in secrets.yaml
    persistentVolume:
        enabled: true
        size: 8Gi

# CouchDB setup job configuration
couchdbSetupJob:
    enabled: true

ingress:
    enabled: true
    host: vibe-cloud-api.example.com # Replace with your domain
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

ingress-nginx:
    controller:
        service:
            annotations:
                service.beta.kubernetes.io/scw-loadbalancer-type: "lb-s"
                service.beta.kubernetes.io/scw-loadbalancer-inbound-ports: "80,443"

clusterIssuer:
    email: admin@socialsystems.io
