# Default values for vibe-cloud-instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- A unique identifier for this instance. Used for naming resources.
instanceIdentifier: "vibe-test-01" # Updated from temp values

# -- Override the namespace for all resources in this chart.
# If not set, Helm's default namespace or the namespace provided with --namespace flag will be used.
namespaceOverride: ""

# -- Configuration for Kubernetes Secrets
secrets:
    # -- If true, Helm will create secrets for CouchDB and JWT. If false, you must provide existing secrets.
    create: true
    # -- Name of an existing secret containing the CouchDB username and password. Used if secrets.create is false.
    # existingCouchdbSecret: ""
    # -- Name of an existing secret containing the JWT secret. Used if secrets.create is false.
    # existingJwtSecret: ""

vibeApp:
    nameOverride: "" # If you want to override the name of the vibe-app deployment/service
    replicaCount: 1
    image:
        repository: sslorg/vibe-cloud-api # Corrected repository name
        pullPolicy: Always # Ensure latest image is pulled
        # Overrides the image tag whose default is the chart appVersion.
        tag: "latest" # Updated from temp values
    service:
        type: ClusterIP
        port: 80
        targetPort: 3000 # The port your Vibe Cloud app listens on
    # Environment variables for the Vibe App
    # Example:
    # env:
    #   COUCHDB_URL: "http://{{ .Release.Name }}-couchdb:5984"
    #   COUCHDB_USER: "{{ .Values.couchdb.auth.username }}"
    #   COUCHDB_PASSWORD: "{{ .Values.couchdb.auth.password }}" # Consider using secrets for this
    env: {}
    # -- Configuration for Vibe App authentication
    auth:
        # -- JWT secret for signing tokens. If secrets.create is true and this is empty, a random secret will be generated.
        # -- If secrets.create is false, this value is ignored, and existingJwtSecret must be set.
        jwtSecret: ""
    resources:
        # We usually recommend not to specify default resources and to leave this as a conscious
        # choice for the user. This also increases chances charts run on environments with little
        # resources, such as Minikube. If you do want to specify resources, uncomment the following
        # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        # limits:
        #   cpu: 100m
        #   memory: 128Mi
        # requests:
        #   cpu: 100m
        #   memory: 128Mi
        {} # No default resources

couchdb:
    nameOverride: "" # If you want to override the name of the couchdb statefulset/service
    image:
        repository: couchdb
        pullPolicy: IfNotPresent
        tag: "3.3.3" # Specify a stable CouchDB version
    auth:
        # It's STRONGLY recommended to use secrets for credentials.
        # -- CouchDB username. If secrets.create is true and this is empty, a random username will be generated.
        # -- If secrets.create is false, this value is ignored, and existingCouchdbSecret must be set.
        username: ""
        # -- CouchDB password. If secrets.create is true and this is empty, a random password will be generated.
        # -- If secrets.create is false, this value is ignored, and existingCouchdbSecret must be set.
        password: ""
        # Note: existingSecret functionality is handled by the top-level 'secrets.existingCouchdbSecret' now.
    persistence:
        enabled: true # Temporarily disable persistence for debugging PVC issue
        size: 5Gi # Default size for CouchDB data volume, reduced for cost optimization
        # storageClassName: "" # If you want to specify a storage class, e.g., "standard", "gp2"
        # existingClaim: "" # If you have an existing PVC
    service:
        type: ClusterIP
        port: 5984 # Default CouchDB port
    resources:
        # limits:
        #   cpu: 500m
        #   memory: 512Mi
        # requests:
        #   cpu: 250m
        #   memory: 256Mi
        {} # No default resources
    setupJob:
        enabled: true # Enable the job to set up system databases

ingress:
    enabled: true
    className: "traefik" # Updated from temp values
    annotations:
        # Only include annotations needed for the working setup
        "cert-manager.io/cluster-issuer": "letsencrypt-prod"
    # The host for the Ingress resource.
    host: "test-cloud.vibeapp.dev" # Updated from temp values
    # mainDomain: "vibe.example.com" # Removed, host is now explicit
    tls:
        # Secrets must be manually created in the namespace.
        # Or, if using cert-manager, it will create them.
        # - secretName: chart-example-tls
        #   hosts:
        #     - chart-example.local
        [] # Keep empty, cert-manager handles this
