services:
    couchdb:
        image: couchdb:3.5
        ports:
            - "5984:5984"
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=password
    couchdb-setup:
        image: curlimages/curl:latest
        depends_on:
            - couchdb
        command: >
            /bin/sh -c "
              set -ex;
              echo 'Waiting for CouchDB...';
              until curl -s -f http://couchdb:5984/; do
                sleep 5;
              done;
              echo 'CouchDB is up.';
              COUCHDB_ENDPOINT='http://admin:password@couchdb:5984';
              curl -X PUT $${COUCHDB_ENDPOINT}/_users || true;
              curl -X PUT $${COUCHDB_ENDPOINT}/_replicator || true;
              curl -X PUT $${COUCHDB_ENDPOINT}/_global_changes || true;
              echo 'Configuring CouchDB CORS...';
              curl -X PUT $${COUCHDB_ENDPOINT}/_config/httpd/enable_cors -d '\"true\"';
              curl -X PUT $${COUCHDB_ENDPOINT}/_config/cors/origins -d '\"http://localhost:5000\"';
              curl -X PUT $${COUCHDB_ENDPOINT}/_config/cors/credentials -d '\"true\"';
              curl -X PUT $${COUCHDB_ENDPOINT}/_config/cors/methods -d '\"GET, PUT, POST, HEAD, DELETE\"';
              curl -X PUT $${COUCHDB_ENDPOINT}/_config/cors/headers -d '\"accept, authorization, content-type, origin, referer, x-csrf-token\"';
              echo 'CouchDB setup complete.';
            "
    minio:
        image: minio/minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        command: server /data --console-address ":9001"
    vibe-cloud-api:
        build:
            context: ../../
            dockerfile: apps/vibe-cloud-api/Dockerfile
        ports:
            - "5000:5000"
        environment:
            - COUCHDB_URL=http://couchdb:5984
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=password
        depends_on:
            - couchdb-setup
            - minio
    vibe-web:
        build:
            context: ../../
            dockerfile: apps/vibe-web/Dockerfile
        ports:
            - "3001:3001"
