[serve]
dir = "build"
port = 5000

[build]
outdir = "build"
entrypoints = ["src/frontend.tsx"]
target = "browser"

[plugins]
"bun-plugin-tailwind" = {}

[resolve]
alias = { "react" = "./node_modules/react" }
