apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: vibe-control-plane-cluster-rolebinding
subjects:
    - kind: ServiceAccount
      name: vibe-control-plane-sa
      namespace: vibe-control-plane # Namespace of the ServiceAccount
roleRef:
    kind: ClusterRole # Referencing the ClusterRole created above
    name: vibe-control-plane-cluster-role
    apiGroup: rbac.authorization.k8s.io
