services:
  postgres:
        image: postgres:16-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=vibe
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d vibe"]
            interval: 5s
            timeout: 3s
            retries: 20
        volumes:
            - postgres-data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4:8.12
        depends_on:
            - postgres
        ports:
            - "5051:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@example.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        volumes:
            - pgadmin-data:/var/lib/pgadmin

  minio:
        image: minio/minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  couchdb:
    image: couchdb:3.5
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
  couchdb-setup:
    image: curlimages/curl:latest
    depends_on:
      - couchdb
    command: >
      /bin/sh -c "
        set -ex;
        echo 'Waiting for CouchDB...';
        until curl -s -f http://couchdb:5984/; do
          sleep 5;
        done;
        echo 'CouchDB is up.';
        COUCHDB_ENDPOINT='http://admin:password@couchdb:5984';
        curl -X PUT $${COUCHDB_ENDPOINT}/_users || true;
        curl -X PUT $${COUCHDB_ENDPOINT}/_replicator || true;
        curl -X PUT $${COUCHDB_ENDPOINT}/_global_changes || true;
        echo 'CouchDB setup complete.';
      "

volumes:
    postgres-data:
    pgadmin-data:
    minio-data:
