# docker-compose.yml
services:
    vibe-cloud:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            - PORT=5000
            - HOST=0.0.0.0
            - DENO_ENV=development
        depends_on:
            - couchdb
        restart: unless-stopped
        networks:
            - vibe-network

    couchdb:
        image: couchdb:3.4.2
        container_name: vibe-couchdb
        environment:
            - COUCHDB_USER=${COUCHDB_ADMIN_USER}
            - COUCHDB_PASSWORD=${COUCHDB_ADMIN_PASSWORD}
            - COUCHDB_SECRET=${COUCHDB_SECRET}
            #- NODENAME=couchdb@vibe-couchdb
        volumes:
            - couchdb_data:/opt/couchdb/data
        ports:
            - "5984:5984"
        networks:
            - vibe-network
        restart: always

networks:
    vibe-network:
        driver: bridge

volumes:
    couchdb_data:
