# docker-compose.yml
services:
    vibe-cloud:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            - PORT=5000
            - HOST=0.0.0.0
            - TURN_PORT=3478
            - TURN_REALM=vibe.local
            - TURN_AUTH_SECRET=${TURN_AUTH_SECRET}
            - NODE_ENV=development
            - LOG_LEVEL=debug
            - COTURN_HOST=coturn
        volumes:
            - ./logs:/app/logs
        depends_on:
            - coturn
        restart: unless-stopped
        networks:
            - vibe-network

    couchdb:
        image: couchdb:3.4.2
        container_name: vibe-couchdb
        environment:
            - COUCHDB_USER=${COUCHDB_ADMIN_USER}
            - COUCHDB_PASSWORD=${COUCHDB_ADMIN_PASSWORD}
            - COUCHDB_SECRET=${COUCHDB_SECRET}
            #- NODENAME=couchdb@vibe-couchdb
        volumes:
            - couchdb_data:/opt/couchdb/data
        ports:
            - "5984:5984"
        networks:
            - vibe-network
        restart: always

    coturn:
        image: coturn/coturn:latest
        ports:
            - "3478:3478/tcp"
            - "3478:3478/udp"
            - "5349:5349/tcp"
            - "5349:5349/udp"
            # - "49152-65535:49152-65535/udp" # port range for prod
            - "50000-50010:50000-50010/udp"
        environment:
            - TURN_PORT=3478
            - TURN_PORT_TLS=5349
            - TURN_USERNAME=vibe
            - TURN_REALM=vibe.local
            - TURN_SECRET=${TURN_AUTH_SECRET}
        command: >
            -n --log-file=stdout
            --lt-cred-mech --use-auth-secret
            --static-auth-secret=${TURN_AUTH_SECRET}
            --realm=vibe.local
            --no-tls
            --no-dtls
            --min-port=49152
            --max-port=65535
            --allowed-peer-ip=0.0.0.0
        restart: unless-stopped
        networks:
            - vibe-network

networks:
    vibe-network:
        driver: bridge

volumes:
    couchdb_data:
