# docker-compose.yml
services:

    couchdb:
        image: couchdb:3.4.2
        env_file:
            - .env        
        container_name: vibe-couchdb
        environment:
            - COUCHDB_USER=${COUCHDB_ADMIN_USER}
            - COUCHDB_PASSWORD=${COUCHDB_ADMIN_PASSWORD}
            - COUCHDB_SECRET=${COUCHDB_SECRET}
            #- NODENAME=couchdb@vibe-couchdb
        volumes:
            - couchdb_data:/opt/couchdb/data
        ports:
            - "5984:5984"
        networks:
            - vibe-network
        restart: always

    minio:
        image: minio/minio
        env_file:
            - .env
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USERNAME}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server /data --console-address :9001
        ports:
            - "${MINIO_PORT}:${MINIO_PORT}"
            - "9001:9001"
        volumes:
            - minio_data:/data
        networks:
            - vibe-network

networks:
    vibe-network:
        driver: bridge

volumes:
    couchdb_data:
    minio_data:
