apiVersion: v1
kind: Service
metadata:
    name: couchdb
    namespace: vibe-cloud-services
    labels:
        app: couchdb
spec:
    ports:
        - port: 5984
          name: couchdb-port
    selector:
        app: couchdb
    # type: ClusterIP # Default, suitable for internal access
