apiVersion: v1
kind: Service
metadata:
    name: vibe-cloud-app-svc
    namespace: vibe-cloud-services
    labels:
        app: vibe-cloud-app
spec:
    type: ClusterIP # Internal access only since we are using Ingress
    ports:
        - port: 80
          targetPort: 3000
          protocol: TCP
          name: http
    selector:
        app: vibe-cloud-app
