apiVersion: v1
kind: Service
metadata:
    name: vibe-cloud-app-svc
    namespace: vibe-cloud-services
    labels:
        app: vibe-cloud-app
spec:
    type: LoadBalancer # Exposes the service externally using a cloud provider's load balancer
    ports:
        - port: 80 # Port the LoadBalancer will listen on
          targetPort: 3000 # Port the vibe-cloud-app container listens on
          protocol: TCP
          name: http
    selector:
        app: vibe-cloud-app
