name: Apply Terraform

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "infra/terraform/**"

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.2.5

            - name: Terraform Init
              run: terraform init
              working-directory: ./infra/terraform
              env:
                  SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
                  SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
                  TF_VAR_scw_project_id: ${{ secrets.SCALEWAY_PROJECT_ID }}
                  TF_VAR_scw_region: "fr-par"
                  TF_VAR_scw_zone: "fr-par-1"
                  TF_VAR_k8s_version: "1.31.2"

            - name: Terraform Plan
              run: terraform plan -out=plan.tfplan
              working-directory: ./infra/terraform
              env:
                  SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
                  SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
                  TF_VAR_scw_project_id: ${{ secrets.SCALEWAY_PROJECT_ID }}
                  TF_VAR_scw_region: "fr-par"
                  TF_VAR_scw_zone: "fr-par-1"
                  TF_VAR_k8s_version: "1.31.2"

            - name: Terraform Apply
              run: terraform apply -auto-approve plan.tfplan
              working-directory: ./infra/terraform
              env:
                  SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
                  SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
                  TF_VAR_scw_project_id: ${{ secrets.SCALEWAY_PROJECT_ID }}
                  TF_VAR_scw_region: "fr-par"
                  TF_VAR_scw_zone: "fr-par-1"
                  TF_VAR_k8s_version: "1.31.2"
