name: Apply Terraform

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "infra/terraform/**"

jobs:
    terraform:
        runs-on: ubuntu-latest
        environment: production # Add this for protection rules
        env:
            # For Scaleway Provider
            SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
            SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
            SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCALEWAY_PROJECT_ID }}
            SCW_DEFAULT_REGION: "fr-par"
            SCW_DEFAULT_ZONE: "fr-par-1"
            # For S3 Backend
            AWS_ACCESS_KEY_ID: ${{ secrets.SCALEWAY_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
            # For Terraform Variables
            TF_VAR_k8s_version: "1.31.2"
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.2.5

            - name: Terraform Init
              run: terraform init
              working-directory: ./infra/terraform

            - name: Terraform Plan
              run: terraform plan -out=plan.tfplan
              working-directory: ./infra/terraform

            - name: Terraform Apply
              run: terraform apply -auto-approve plan.tfplan
              working-directory: ./infra/terraform
