name: Build and Push vibe-cloud-api

on:
    workflow_dispatch:

    # Will be removed once deploy-helm-chart.yaml is fixed
    # To re-enable automated deployments on changes to the API or infrastructure,
    # uncomment the following lines and remove 'workflow_dispatch:'.
    # push:
    #   branches:
    #     - main
    #   paths:
    #     - "apps/vibe-cloud-api/**"

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to Scaleway Container Registry
              uses: docker/login-action@v2
              with:
                  registry: rg.fr-par.scw.cloud
                  username: nologin
                  password: ${{ secrets.SCALEWAY_SECRET_KEY }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: ./apps/vibe-cloud-api
                  push: true
                  tags: rg.fr-par.scw.cloud/vibe-registry/vibe-cloud-api:latest
