name: Build, Push, and Deploy

on:
    push:
        branches:
            - main # Or your primary branch

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Scaleway Container Registry
              uses: docker/login-action@v2
              with:
                  registry: rg.fr-par.scw.cloud/vibe-registry
                  username: nologin
                  password: ${{ secrets.SCALEWAY_SECRET_KEY }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./apps/vibe-cloud-api/Dockerfile
                  push: true
                  tags: rg.fr-par.scw.cloud/vibe-registry/vibe-cloud-api:${{ github.sha }}

            - name: Setup Scaleway CLI
              uses: scaleway/action-scw@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
                  secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
                  export-config: true
                  default-organization-id: ${{ secrets.SCALEWAY_ORGANIZATION_ID }}
                  default-project-id: ${{ secrets.SCALEWAY_PROJECT_ID }}

            - name: Generate Kubeconfig
              run: |
                  CLUSTER_ID=$(scw k8s cluster list name=vibe-kapsule region=fr-par -o json | jq -r '.[0].id')
                  scw k8s kubeconfig install $CLUSTER_ID region=fr-par
                  echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

            - name: Set up Helm
              uses: azure/setup-helm@v3
              with:
                  version: "v3.9.4"

            - name: Update Helm dependencies
              run: helm dependency update ./infra/helm/vibe-cloud-api

            - name: Create secrets file
              run: |
                  cat << EOF > ./infra/helm/vibe-cloud-api/secrets.yaml
                  config:
                    jwtSecret: "${{ secrets.JWT_SECRET }}"
                    instanceIdSecret: "${{ secrets.INSTANCE_ID_SECRET }}"
                    scalewayAccessKey: "${{ secrets.SCALEWAY_ACCESS_KEY }}"
                    scalewaySecretKey: "${{ secrets.SCALEWAY_SECRET_KEY }}"
                  couchdb:
                    auth:
                      username: "admin"
                      password: "${{ secrets.COUCHDB_PASSWORD }}"
                  EOF

            - name: Deploy Helm chart
              run: |
                  helm upgrade --install vibe-cloud-api ./infra/helm/vibe-cloud-api \
                    --namespace vibe --create-namespace \
                    --values ./infra/helm/vibe-cloud-api/secrets.yaml \
                    --set image.tag=${{ github.sha }}
