name: Deploy Vibe Cloud UI

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "apps/vibe-cloud-ui/**"
            - "infra/helm/vibe-cloud-ui/**"
            - ".github/workflows/deploy-ui.yaml"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Scaleway Container Registry
              uses: docker/login-action@v2
              with:
                  registry: rg.fr-par.scw.cloud/vibe-registry
                  username: nologin
                  password: ${{ secrets.SCALEWAY_SECRET_KEY }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./apps/vibe-cloud-ui/Dockerfile
                  push: true
                  tags: rg.fr-par.scw.cloud/vibe-registry/vibe-cloud-ui:${{ github.sha }}
                  build-args: |
                      APP_VERSION=${{ github.sha }}

            - name: Setup Scaleway CLI
              uses: scaleway/action-scw@v0
              with:
                  version: v2.41.0
                  access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
                  secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
                  export-config: true
                  default-organization-id: ${{ secrets.SCALEWAY_ORGANIZATION_ID }}
                  default-project-id: ${{ secrets.SCALEWAY_PROJECT_ID }}

            - name: Generate Kubeconfig
              run: |
                  CLUSTER_ID=$(scw k8s cluster list name=vibe-kapsule region=fr-par -o json | jq -r '.[0].id')
                  scw k8s kubeconfig install $CLUSTER_ID region=fr-par
                  echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

            - name: Set up Helm
              uses: azure/setup-helm@v3
              with:
                  version: "v3.9.4"

            - name: Update Helm dependencies
              run: helm dependency update ./infra/helm/vibe-cloud-ui

            - name: Deploy Helm Chart
              run: |
                  helm upgrade --install vibe-cloud-ui ./infra/helm/vibe-cloud-ui \
                    --namespace vibe --create-namespace \
                    --values ./infra/helm/vibe-cloud-ui/values.yaml \
                    --set image.tag=${{ github.sha }}

            - name: Wait for Certificate Readiness
              run: |
                  kubectl wait --for=condition=Ready certificate/vibe-cloud-ui-tls -n vibe --timeout=5m
