name: Deploy Vibe Cloud API

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "apps/vibe-cloud-api/**"
            - "infra/helm/vibe-cloud-api/**"
            - ".github/workflows/deploy-api.yaml"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Scaleway Container Registry
              uses: docker/login-action@v2
              with:
                  registry: rg.fr-par.scw.cloud/vibe-registry
                  username: nologin
                  password: ${{ secrets.SCALEWAY_SECRET_KEY }}

            - name: Prepare App Version
              id: prep_version
              run: |
                  GIT_SHA_SHORT=$(echo "${{ github.sha }}" | cut -c1-7)
                  PKG_JSON_PATH="./apps/vibe-cloud-api/package.json"
                  EFFECTIVE_VERSION=$GIT_SHA_SHORT
                  if [ -f "$PKG_JSON_PATH" ]; then
                    PKG_VERSION=$(jq -r .version "$PKG_JSON_PATH")
                    if [ "$PKG_VERSION" != "null" ] && [ -n "$PKG_VERSION" ]; then
                      EFFECTIVE_VERSION="${PKG_VERSION}-${GIT_SHA_SHORT}"
                    else
                      echo "Warning: Could not read version from $PKG_JSON_PATH, or version was null/empty."
                    fi
                  else
                    echo "Warning: No package.json found at $PKG_JSON_PATH."
                  fi
                  echo "EFFECTIVE_APP_VERSION=${EFFECTIVE_VERSION}" >> $GITHUB_ENV
                  echo "Determined APP_VERSION: ${EFFECTIVE_VERSION}"

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./apps/vibe-cloud-api/Dockerfile
                  push: true
                  tags: rg.fr-par.scw.cloud/vibe-registry/vibe-cloud-api:latest,rg.fr-par.scw.cloud/vibe-registry/vibe-cloud-api:${{ github.sha }}
                  build-args: |
                      APP_VERSION=${{ env.EFFECTIVE_APP_VERSION }}

            - name: Setup Scaleway CLI
              uses: scaleway/action-scw@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  version: v2.41.0
                  access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
                  secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
                  export-config: true
                  default-organization-id: ${{ secrets.SCALEWAY_ORGANIZATION_ID }}
                  default-project-id: ${{ secrets.SCALEWAY_PROJECT_ID }}

            - name: Generate Kubeconfig
              run: |
                  CLUSTER_ID=$(scw k8s cluster list name=vibe-kapsule region=fr-par -o json | jq -r '.[0].id')
                  scw k8s kubeconfig install $CLUSTER_ID region=fr-par
                  echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

            - name: Set up Helm
              uses: azure/setup-helm@v3
              with:
                  version: "v3.9.4"

            - name: Add CouchDB Helm repository
              run: helm repo add couchdb https://apache.github.io/couchdb-helm

            - name: Update Helm dependencies
              run: helm dependency update ./infra/helm/vibe-cloud-api

            - name: Create secrets file
              run: |
                  cat << EOF > ./infra/helm/vibe-cloud-api/secrets.yaml
                  config:
                    jwtSecret: "${{ secrets.JWT_SECRET }}"
                    instanceIdSecret: "${{ secrets.INSTANCE_ID_SECRET }}"
                    scalewayAccessKey: "${{ secrets.SCALEWAY_ACCESS_KEY }}"
                    scalewaySecretKey: "${{ secrets.SCALEWAY_SECRET_KEY }}"
                    encryptionMasterKey: "${{ secrets.ENCRYPTION_MASTER_KEY }}"
                    sessionSecret: "${{ secrets.SESSION_SECRET }}"
                    vibeCloudUiUrl: "http://vibe-cloud-ui-service:80"
                    corsOrigin: "${{ secrets.CORS_ORIGIN }},https://vibe-feeds.vercel.app,https://vibe-collections.vercel.app,https://${{ secrets.INGRESS_HOST }},http://${{ secrets.INGRESS_HOST }}"
                  couchdb:
                    adminUsername: "admin"
                    adminPassword: "${{ secrets.COUCHDB_PASSWORD }}"
                    couchdbConfig:
                      couchdb:
                        uuid: "${{ secrets.COUCHDB_UUID }}"
                  EOF

            - name: Deploy Helm chart
              run: |
                  helm upgrade --install vibe-cloud-api ./infra/helm/vibe-cloud-api \
                    --namespace vibe --create-namespace \
                    --values ./infra/helm/vibe-cloud-api/secrets.yaml \
                    --set image.tag=${{ github.sha }} \
                    --set ingress.host=${{ secrets.INGRESS_HOST }} \
                    --set clusterIssuer.email=${{ secrets.CLUSTER_ISSUER_EMAIL }}

            - name: Wait for API Certificate Readiness
              run: |
                  kubectl wait --for=condition=Ready certificate/vibe-cloud-api-tls -n vibe --timeout=5m

            - name: Wait for CouchDB Certificate Readiness
              run: |
                  kubectl wait --for=condition=Ready certificate/vibe-cloud-api-couchdb-tls -n vibe --timeout=5m
