name: Docker Publish vibe-cloud

on:
    push:
        branches:
            - main # Or your primary branch
        paths:
            - "vibe-cloud/**" # Only run if vibe-cloud code changes

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read # To checkout the repository

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: sslorg/vibe-cloud
                  tags: |
                      type=sha,prefix=,suffix=,format=short
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./vibe-cloud # Path to the Dockerfile directory
                  file: ./vibe-cloud/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
