name: Build and Push Docker Images

on:
    push:
        branches:
            - main
        paths:
            - "vibe-web/**"
            - "apps/contacts/**"
            - "vibe-sdk/**"
            - "vibe-react/**"

jobs:
    changes:
        runs-on: ubuntu-latest
        outputs:
            vibe-web: ${{ steps.filter.outputs.vibe-web }}
            contacts: ${{ steps.filter.outputs.contacts }}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                      vibe-web:
                        - 'vibe-web/**'
                        - 'vibe-sdk/**'
                        - 'vibe-react/**'
                      contacts:
                        - 'apps/contacts/**'
                        - 'vibe-sdk/**'
                        - 'vibe-react/**'

    build-vibe-web:
        needs: changes
        if: ${{ needs.changes.outputs.vibe-web == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: docker/setup-buildx-action@v3
            - name: Generate build timestamp
              id: timestamp
              run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
            - uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./vibe-web/Dockerfile
                  push: true
                  tags: |
                      ${{ secrets.DOCKER_HUB_USERNAME }}/vibe-web:latest
                      ${{ secrets.DOCKER_HUB_USERNAME }}/vibe-web:${{ steps.timestamp.outputs.timestamp }}
                  cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/vibe-web:buildcache
                  cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/vibe-web:buildcache,mode=max

    build-contacts:
        needs: changes
        if: ${{ needs.changes.outputs.contacts == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: docker/setup-buildx-action@v3
            - name: Generate build timestamp
              id: timestamp
              run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
            - uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./apps/contacts/Dockerfile
                  push: true
                  tags: |
                      ${{ secrets.DOCKER_HUB_USERNAME }}/vibe-contacts:latest
                      ${{ secrets.DOCKER_HUB_USERNAME }}/vibe-contacts:${{ steps.timestamp.outputs.timestamp }}
                  cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/vibe-contacts:buildcache
                  cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/vibe-contacts:buildcache,mode=max
