name: Build and Push Docker Image

on:
    push:
        branches:
            - main
        paths:
            - "vibe-web/**"

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Generate build timestamp
              id: timestamp
              run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./vibe-web/Dockerfile
                  push: true
                  tags: |
                      ${{ secrets.DOCKER_HUB_USERNAME }}/vibe-web:latest
                      ${{ secrets.DOCKER_HUB_USERNAME }}/vibe-web:${{ steps.timestamp.outputs.timestamp }}
                  cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/vibe-web:buildcache
                  cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/vibe-web:buildcache,mode=max
