name: Docker Publish vibe-cloud

on:
    push:
        branches:
            - main # Or your primary branch
        paths:
            - "vibe-cloud/vibe-cloud-api/**" # Trigger on API changes
            - "vibe-cloud/vibe-cloud-control-plane/**" # Trigger on Control Plane changes

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read # To checkout the repository
        strategy:
            matrix:
                service: [api, control-plane] # Define the services to build
                include: # Map service names to context paths
                    - service: api
                      context: ./vibe-cloud/vibe-cloud-api
                      dockerfile_path: ./vibe-cloud/vibe-cloud-api/Dockerfile
                    - service: control-plane
                      context: . # Build context for control-plane is now monorepo root
                      dockerfile_path: ./vibe-cloud/vibe-cloud-control-plane/Dockerfile

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker - ${{ matrix.service }}
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: sslorg/vibe-cloud-${{ matrix.service }} # Use matrix service name in image name
                  tags: |
                      type=sha,prefix=,suffix=,format=short
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Prepare App Version - ${{ matrix.service }}
              id: prep_version
              run: |
                  GIT_SHA_SHORT=$(echo "${{ github.sha }}" | cut -c1-7)
                  # Default to just SHA if package.json or its version is not found/valid
                  EFFECTIVE_VERSION=$GIT_SHA_SHORT
                  # Adjust PKG_JSON_PATH based on service, as control-plane's context is now '.'
                  if [ "${{ matrix.service }}" == "control-plane" ]; then
                    PKG_JSON_PATH="./vibe-cloud/vibe-cloud-control-plane/package.json"
                  else
                    PKG_JSON_PATH="${{ matrix.context }}/package.json"
                  fi

                  if [ -f "$PKG_JSON_PATH" ]; then
                    PKG_VERSION=$(jq -r .version "$PKG_JSON_PATH")
                    if [ "$PKG_VERSION" != "null" ] && [ -n "$PKG_VERSION" ]; then
                      EFFECTIVE_VERSION="${PKG_VERSION}-${GIT_SHA_SHORT}"
                    else
                      echo "Warning: Could not read version from $PKG_JSON_PATH, or version was null/empty."
                    fi
                  else
                    echo "Warning: No package.json found at $PKG_JSON_PATH for service ${{ matrix.service }}."
                  fi
                  echo "EFFECTIVE_APP_VERSION=${EFFECTIVE_VERSION}" >> $GITHUB_ENV
                  echo "Determined APP_VERSION for ${{ matrix.service }}: ${EFFECTIVE_VERSION}"

            - name: Build and push Docker image - ${{ matrix.service }}
              uses: docker/build-push-action@v5
              with:
                  context: ${{ matrix.context }} # Use matrix context path
                  file: ${{ matrix.dockerfile_path }} # Use dockerfile_path from matrix
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      APP_VERSION=${{ env.EFFECTIVE_APP_VERSION }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

    trigger-rollout:
        needs: build-and-push-image # Runs after images are built and pushed
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' # Only run for pushes to the main branch

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Kubeconfig
              run: |
                  mkdir -p ~/.kube
                  echo "${{ secrets.KUBE_CONFIG_DATA }}" > ~/.kube/config
                  chmod 600 ~/.kube/config
              env:
                  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

            - name: Install kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: "v1.29.0" # Specify a kubectl version or let it default
              id: install

            - name: Restart vibe-control-plane deployment
              if: success() # Only run if previous steps succeeded
              run: |
                  echo "Attempting to restart vibe-control-plane-deployment..."
                  kubectl rollout restart deployment vibe-control-plane-deployment -n vibe-control-plane
              continue-on-error: true # Set to false if a failed rollout should fail the workflow

            - name: Restart vibe-cloud-api deployments
              if: success()
              run: |
                  echo "Attempting to restart all vibe-cloud-api (vibe-app) deployments..."
                  # This command assumes your vibe-cloud-api deployments have a common label like 'app.kubernetes.io/name=vibe-app'.
                  # Adjust the label selector (-l) if your Helm chart uses a different common label for these deployments.
                  # It gets deployments across all namespaces.
                  DEPLOYMENTS_TO_RESTART=$(kubectl get deployments --all-namespaces -l 'app.kubernetes.io/name=vibe-app' -o jsonpath='{range .items[*]}{.metadata.namespace}{"/"}{.metadata.name}{"\n"}{end}')

                  if [ -z "$DEPLOYMENTS_TO_RESTART" ]; then
                    echo "No vibe-cloud-api deployments found with label 'app.kubernetes.io/name=vibe-app'."
                  else
                    echo "Found the following vibe-cloud-api deployments to restart:"
                    echo "$DEPLOYMENTS_TO_RESTART"
                    echo "$DEPLOYMENTS_TO_RESTART" | while IFS= read -r item; do
                      NAMESPACE=$(echo "$item" | cut -d'/' -f1)
                      DEPLOYMENT=$(echo "$item" | cut -d'/' -f2)
                      if [ -n "$NAMESPACE" ] && [ -n "$DEPLOYMENT" ]; then
                        echo "Restarting deployment '$DEPLOYMENT' in namespace '$NAMESPACE'..."
                        kubectl rollout restart deployment "$DEPLOYMENT" -n "$NAMESPACE"
                      else
                        echo "Skipping invalid item: $item"
                      fi
                    done
                  fi
              continue-on-error: true # Set to false if a failed rollout should fail the workflow
