name: Apply Terraform

on:
    workflow_dispatch:

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.2.5

            - name: Terraform Init
              run: terraform init
              working-directory: ./infra/terraform
              env:
                  SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
                  SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}

            - name: Terraform Apply
              run: terraform apply -auto-approve
              working-directory: ./infra/terraform
              env:
                  SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
                  SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
